version: '3'

tasks:
  default:
    cmds:
      - task: benchmark
      - task: build
      - task: fmt
      - task: test
      - task: vet

  benchmark:
    cmds:
      - go test -bench=. -count 3 

  build:
    cmds:
      - go build -v -ldflags "-s -w" -o "bin/ddt" cmd/ddt/*.go

  fmt:
    cmds:
      - gofmt -d .

  test:
    cmds:
      - go test -p 1 -v ./... -cover

  vet:
    cmds:
      - go vet -v ./...
